custom:
  config: ${file(./lambda/${opt:stage}.env.yml):config}
  env: ${file(./lambda/${opt:stage}.env.yml):env}
  apigwBinary: # Library to add support for api gateway binary types
    types:
      - '*/*'

service: vinyl-search-hosting-service

plugins:
  - serverless-offline
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage}
  memorySize: 192
  timeout: 10
  region: ${self:custom.config.region}

package:
  exclude: # By default exclude all files
    - '*/**'
  include: # Then start adding the relevant files/folder to package
    - 'node_modules/aws-serverless-express/**'
    - 'node_modules/binary-case/**'
    - 'node_modules/type-is/**'
    - 'node_modules/media-typer/**'
    - 'node_modules/mime-types/**'
    - 'node_modules/mime-db/**'
    - 'dist/**'
    - 'lambda.js'
functions:
  web-hosting:
    name:  ${self:service}-${opt:stage}
    handler: lambda.handler # A file lambda.js will hold fn handler

    events:
      - http: GET {proxy+}
      - http: GET /
