package:
  exclude:
    - '**/*'
  include:
    - node_modules/**
    - utils/**
    - userpool-trigger-service/**


service: vinyl-search-userpool-service

functions:
  userpool-trigger-service:
    handler: userpool-trigger-service/user-pool-triggers.handler
    name:  ${self:service}-${opt:stage}
    environment:
      MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
      user_pool_id: ${self:custom.config.user_pool_id}