package:
  exclude:
    - '**/*'
  include:
    - node_modules/**
    - utils/**
    - administration-service/**

service: vinyl-search-admin-service

functions:
  administration-service:
    handler: administration-service/admin-main.main
    name:  ${self:service}-${opt:stage}
    environment:
      MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
      user_pool_id: ${self:custom.config.user_pool_id}
      BUCKET_NAME: ${self:custom.env.BUCKET_NAME}
      BUCKET_REGION: ${self:custom.env.BUCKET_REGION}
    events:
      - http:
          method: get
          path: users/{userUid}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: admin-users
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: admin-users/{userUid}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: post
          path: admin-users/{userUid}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: records
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: records/{recordId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: forum
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: any
          path: market
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: reports
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: post
          path: reports/{reportId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: any
          path: market/{postId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: forum/{postId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
